name: Lint & Test

on: [push]
jobs:
    lint_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install dependencies
              run: yarn

            - name: Linting
              run: yarn lint

            - name: Unit Tests
              run: yarn test
